### ISSUE TITLE
如何使用Node.js

### ISSUE THREAD

**Issue by kevinliu1116** [ptxmotc/Sample-code#4]
想請教下載下來的Node.js檔案後該如何使用，是否要將裡面的內容和Node.js的程式內容檔案互換?

**Comment by NoobTW** [comment]
這個 repository 的 sample.js 只是範例，大致操作了把 AppID 和 AppKey 用 jsSHA 處理後，然後用 axios 去呼叫原本的 API 而已。

存取 API 的部分可以用常見的 request、fetch、axios 都沒問題。
